name: Snykcodescan
on:
  push

jobs:
  SNykCode:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: SnykcodeScanning
      run: |
         echo "----------Download Latest Snyk CLI-----------"
         curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.1200.0/snyk-linux"
         chmod +x snyk
         ls -lrt
         echo "----------Authenticating Snyk-----------"
         ./snyk auth ${{secrets.Snyk_token}}
         echo "---snyk config with organization----"
         ./snyk config set --org="01ece29f-d384-4e4e-bfed-b87a65f36130"
         echo "----------Snyk Code Scanning-----------"
         ./snyk code test --report --project-name="javacode"
             
             
             
             
             
